version: '3'
services:
  app:
    build:
      context: ./rectangle-splitter
    container_name: shapes-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
